import { createAdminClient } from "@/lib/supabase/admin";
import { formatLkr } from "@/lib/config";
import { createHash } from "node:crypto";
import Link from "next/link";
import { ReceiptForm } from "@/components/receipt-form";
export default async function ConfirmationPage({params,searchParams}:{params:Promise<{reference:string}>;searchParams:Promise<{access?:string}>}){
 const {reference}=await params;const {access}=await searchParams;const db=createAdminClient();let order:null|{public_reference:string;total_lkr:number;payment_status:string;order_status:string}=null;let instructions="";let phone="+94741389234";
 if(db){const {data:s}=await db.from("store_settings").select("key,value").in("key",["payment_instructions","whatsapp"]);const settings=Object.fromEntries((s??[]).map(r=>[r.key,r.value]));instructions=String(settings.payment_instructions?.text??"");phone=String(settings.whatsapp??phone);}
 if(db&&access){const hash=createHash("sha256").update(access).digest("hex");const {data}=await db.from("orders").select("public_reference,total_lkr,payment_status,order_status").eq("public_reference",reference).eq("access_token_hash",hash).maybeSingle();order=data;}
 return <section className="page-shell"><p className="eyebrow">DRACO / ORDER RECEIVED</p><h1>THANK<br/><em>YOU.</em></h1>{order?<><p className="page-lede">Your order <strong>{order.public_reference}</strong> has been placed. Keep this reference and access link private.</p><div className="payment-note"><span className="eyebrow">BANK TRANSFER / ADVANCE PAYMENT</span><p>Amount due: {formatLkr(order.total_lkr)}</p><small>{instructions||"Bank details are not configured yet. Contact DRACO before making a transfer. Your order remains pending payment review."}</small></div>{instructions&&order.order_status==="pending_payment"&&<ReceiptForm reference={reference} accessToken={access!}/>}<a className="button button-light" href={`https://wa.me/${phone.replace(/\D/g,"")}?text=${encodeURIComponent(`Hello DRACO, I am following up on order ${order.public_reference}.`)}`} target="_blank" rel="noreferrer">Message DRACO on WhatsApp <span>↗</span></a></>:<div className="page-empty"><h2>Order details require your private access link.</h2><p>This page does not disclose order information without the secure access token.</p><Link href="/track-order" className="text-link">Track an order ↗</Link></div>}</section>;
}
