"use client";
import { FormEvent,useState } from "react";
type EditableProduct={id:string;name:string;price_lkr:number;status:string;category:string};
export function ProductEditor({product}:{product:EditableProduct}){
  const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const r=await fetch("/api/admin/products",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:product.id,name:f.get("name"),price_lkr:Number(f.get("price")),status:f.get("status"),category:f.get("category")})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage("Product updated.");location.reload();}catch(e){setMessage(e instanceof Error?e.message:"Update failed.");}finally{setBusy(false);}}
  async function addVariant(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const r=await fetch("/api/admin/variants",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productId:product.id,size:f.get("size"),color:f.get("color"),sku:f.get("sku"),stock:Number(f.get("stock"))})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage("Variant added.");location.reload();}catch(e){setMessage(e instanceof Error?e.message:"Variant failed.");}finally{setBusy(false);}}
  return <details className="product-editor"><summary>Edit / add variant</summary><form className="admin-form compact" onSubmit={save}><div className="form-pair"><label>Name<input name="name" defaultValue={product.name} required maxLength={120}/></label><label>Price (LKR)<input name="price" type="number" min={1} defaultValue={product.price_lkr} required/></label></div><div className="form-pair"><label>Category<select name="category" defaultValue={product.category}><option value="tshirt">T-shirt</option><option value="hoodie">Hoodie</option><option value="bottoms">Bottoms</option><option value="accessory">Accessory</option></select></label><label>Catalog status<select name="status" defaultValue={product.status}><option value="draft">Draft</option><option value="active">Published</option><option value="archived">Archived</option></select></label></div><button disabled={busy}>Save product changes</button></form><form className="admin-form compact" onSubmit={addVariant}><h3>Add size / color variant</h3><div className="form-pair"><label>Size<input name="size" required maxLength={20}/></label><label>Color<input name="color" required maxLength={50}/></label></div><div className="form-pair"><label>Unique SKU<input name="sku" required maxLength={80}/></label><label>Starting stock<input name="stock" type="number" min={0} defaultValue={0} required/></label></div><button disabled={busy}>Add variant</button></form><p role="status">{message}</p></details>
}
