"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useCart } from "@/components/cart-provider";
import { formatLkr } from "@/lib/config";
type QuoteLine={variant_id:string;name:string;size:string;color:string;price_lkr:number;quantity:number};
type Quote={items:QuoteLine[];subtotal_lkr:number;delivery_lkr:number;discount_lkr:number;total_lkr:number};
export default function CheckoutPage() {
  const {items,clear}=useCart();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [quote,setQuote]=useState<Quote|null>(null);const [quoteError,setQuoteError]=useState("");
  useEffect(()=>{if(!items.length){setQuote(null);return;}const controller=new AbortController();setQuote(null);setQuoteError("");fetch("/api/quote",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({items:items.map(i=>({variantId:i.variantId,quantity:i.quantity}))}),signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error??"Quote unavailable.");setQuote(d as Quote);}).catch(e=>{if(!controller.signal.aborted)setQuoteError(e instanceof Error?e.message:"Quote unavailable.");});return()=>controller.abort();},[items]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");if(!quote){setError(quoteError||"Please wait for the current order total.");setBusy(false);return;}const data=Object.fromEntries(new FormData(event.currentTarget).entries());try{const idempotencyKey=sessionStorage.getItem("draco-order-key")||crypto.randomUUID();sessionStorage.setItem("draco-order-key",idempotencyKey);const response=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json","Idempotency-Key":idempotencyKey},body:JSON.stringify({customer:data,items:items.map(i=>({variantId:i.variantId,quantity:i.quantity})),idempotencyKey})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Order could not be created.");sessionStorage.removeItem("draco-order-key");clear();location.href=`/order-confirmation/${encodeURIComponent(result.reference)}?access=${encodeURIComponent(result.accessToken)}`;}catch(e){setError(e instanceof Error?e.message:"Please try again.");setBusy(false);}}
  if(!items.length)return <section className="page-shell"><p className="eyebrow">CHECKOUT</p><h1>YOUR BAG<br/><em>IS EMPTY.</em></h1><Link className="text-link" href="/collection">Return to collection ↗</Link></section>;
  return <section className="page-shell"><p className="eyebrow">DRACO / CHECKOUT</p><h1>YOUR<br/><em>DETAILS.</em></h1><div className="checkout-layout"><form className="checkout-form" onSubmit={submit}><h2>Delivery details</h2><label>Full name<input name="fullName" required minLength={2} maxLength={100} autoComplete="name"/></label><label>Phone number<input name="phone" required minLength={7} maxLength={24} autoComplete="tel"/></label><label>Email address <span>optional</span><input name="email" type="email" maxLength={254} autoComplete="email"/></label><label>Delivery address<textarea name="address" required minLength={8} maxLength={300} autoComplete="street-address"/></label><div className="form-pair"><label>City / town<input name="city" required minLength={2} maxLength={100} autoComplete="address-level2"/></label><label>District<input name="district" maxLength={80} autoComplete="address-level1"/></label></div><label>Notes <span>optional</span><textarea name="notes" maxLength={500}/></label><div className="payment-note"><span className="eyebrow">PAYMENT METHOD</span><p>Bank transfer / advance payment</p><small>Payment instructions appear after the order is placed. Your order is not confirmed until payment is reviewed.</small></div><button className="button button-light" disabled={busy||!quote}>{busy?"Creating order…":!quote?"Checking total…":"Place order"}<span>↗</span></button><p role="alert" className="form-error">{error||quoteError}</p></form><aside className="checkout-summary"><p className="eyebrow">SERVER-CHECKED ORDER</p>{quote?.items.map(i=><div key={i.variant_id}><span>{i.name} / {i.size} / {i.color} × {i.quantity}</span><b>{formatLkr(i.price_lkr*i.quantity)}</b></div>)}{quote&&<><div><span>Subtotal</span><b>{formatLkr(quote.subtotal_lkr)}</b></div><div><span>Delivery</span><b>{formatLkr(quote.delivery_lkr)}</b></div>{quote.discount_lkr>0&&<div><span>Launch promotion</span><b>−{formatLkr(quote.discount_lkr)}</b></div>}<div className="cart-total"><span>Total</span><strong>{formatLkr(quote.total_lkr)}</strong></div></>}{!quote&&!quoteError&&<p className="checkout-disclaimer">Checking current prices, stock, delivery, and promotion…</p>}<p className="checkout-disclaimer">The server recalculates totals again when placing your order. A quote can change if inventory or promotion availability changes first.</p></aside></div></section>;
}
